FROM golang:alpine

ENV GO15VENDOREXPERIMENT=1
ENV GLIDE='https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-linux-amd64.tar.gz'

RUN apk --no-cache add curl git && \
    curl -L "${GLIDE}" -o glide.tar.gz && \
    tar xzf glide.tar.gz -C /tmp && \
    mv /tmp/linux-amd64/glide /usr/bin/ && \
    rm -f glide.tar.gz && \
    rm -rf /tmp/linux-amd64 && \
    apk del curl

RUN mkdir -p /go/src/github.com/micromdm/micromdm/
WORKDIR /go/src/github.com/micromdm/micromdm/
COPY . /go/src/github.com/micromdm/micromdm/

#RUN glide install
RUN GOGC=500 go build && mv micromdm /

CMD ["/micromdm"]
