version: "2"

services:
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_DB: micromdm
      POSTGRES_USER: micromdm
      POSTGRES_PASSWORD: micromdm
    ports:
      - 5432:5432
