ALTER TABLE devices
  ALTER COLUMN build_version DROP NOT NULL,
  ALTER COLUMN product_name DROP NOT NULL,
  ALTER COLUMN os_version DROP NOT NULL;

ALTER TABLE devices
  ALTER COLUMN build_version DROP DEFAULT,
  ALTER COLUMN product_name DROP DEFAULT,
  ALTER COLUMN os_version DROP DEFAULT;
